development:
  adapter: postgresql
  encoding: unicode
  database: quiz_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: quiz_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: quiz_development
  pool: 5
  timeout: 5000
